language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
rvm:
  - 2.0
install:
  - rvm install 2.0
  - rvm use 2.0
  - gem install bundler
  - bundle install
script: buildr clean package
